/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adventurer;

import adventurer.game.Adventurer;
import adventurer.game.Forest;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        Forest forest = new Forest("carte.txt");
        Adventurer hero = new Adventurer(3, 0);
        hero.advance(forest, "SSSSEEEEEENN");
        System.out.println(hero.coordinates);

        // System.out.println(forest);
    }
}
