/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adventurer;

import adventurer.game.Adventurer;
import adventurer.game.Forest;
import adventurer.geometry.Point;

public class App {

    public static void main(String[] args) {

        Forest forest = new Forest("carte.txt");

        Adventurer hero = new Adventurer(3, 0, forest);

        // hero.advance("SSSSEEEEEENN");
        // System.out.println(hero.coordinates);

        System.out.println(hero);
    }
}
