/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adventurer;

import org.junit.jupiter.api.Test;

import adventurer.game.Adventurer;
import adventurer.game.Forest;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void shouldFindObstacles() {
        Forest forest = new Forest("carte.txt");
        Adventurer hero = new Adventurer(3, 0);

        assertEquals(hero.canAdvance(forest, 'N'), false);

        assertEquals(hero.canAdvance(forest, 'S'), true);

        assertEquals(hero.canAdvance(forest, 'E'), true);

        assertEquals(hero.canAdvance(forest, 'O'), false);

    }

    @Test

    void shouldAvoidObstaclesAndAdvance() {
        Forest forest = new Forest("carte.txt");
        Adventurer hero = new Adventurer(3, 0);
        hero.advance(forest, "SSSSEEEEEENN");

        assertEquals(hero.coordinates.getX(), 9);
        assertEquals(hero.coordinates.getY(), 2);

    }
}
